# -*- coding: utf-8 -*-
"""Copy of Assignment1_Celebal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDODLybMKb4bRNPlkBH9LHt6qFdxJtIW

# Lower Triangular Pattern
"""

r = int(input("Enter the number of rows: "))
for i in range(1, r + 1):
    print("* " * i)

"""#Upper Triangular pattern"""

r = int(input("Enter the number of rows: "))
for i in range(r):
    print("  " * i + "* " * (r - i))

"""#Pyramid shape pattern"""

r = int(input("Enter the number of rows: "))
for i in range(r):
    for j in range(r-i-1):
        print(" ",end="")
    temp=2*i+1
    for j in range(temp):
        print("*",end="")
    print()

